#!/bin/bash
rm -rf tmp/api
# Open pusher.html in a browser window to see storyboard participant's avatars.
# open pusher.html
# Variables
if [[ -z "$1" ]]
  then PORT="3000"
else
  PORT=$1
fi
HOST="http://localhost:$PORT"
# Start the server, dummy.
printf "Waiting for you to start the server on $HOST"
while :
do
  if [[ ! -z `curl -s $HOST` ]]
  then
    break
  fi
done
# user 0
TEMP_VALUE_0=`date +%s | md5`_0
TEST_USER_0="$TEMP_VALUE_0@test0.com"
# # user 1
# TEMP_VALUE_1=`date +%s | md5`_1
# TEST_USER_1="$TEMP_VALUE_1@test1.com"
# TEST_USER_1_AVATAR="$HOST/images/avatar_1.png"
# # user 2
# TEMP_VALUE_2=`date +%s | md5`_2
# TEST_USER_2="$TEMP_VALUE_2@test2.com"
# TEST_USER_2_AVATAR="$HOST/images/avatar_2.png"
# # user 3
# TEMP_VALUE_3=`date +%s | md5`_3
# TEST_USER_3="$TEMP_VALUE_3@test3.com"
# TEST_USER_3_AVATAR="$HOST/images/avatar_3.png"
# # user 3
# TEMP_VALUE_4=`date +%s | md5`_4
# TEST_USER_4="user3friend@test.com" # This comes from user 3's participant create
# TEST_USER_4_AVATAR="$HOST/images/avatar_4.png"
# # Grab the token for subsequent tests
function get_designer_location {
  cat $HEADERS | grep 'Location: ' | grep 'designers' | cut -c 43,43 | tr -d '\r'
}
function get_token {
  cat $HEADERS | grep 'Auth-Token: ' | cut -c 13-44 | tr -d '\r'
}
function get_storyboard_location {
  cat $HEADERS | grep 'Location: ' | grep 'storyboards' | cut -c 45,45 | tr -d '\r'
}
function get_sketch_location {
  cat $HEADERS | grep 'Location: ' | grep 'sketches' | cut -c 42,42 | tr -d '\r'
}
function process_result {
  # Is this the result you were exepecting?
  if [[ -z `cat $HEADERS | grep "$EXPECT"` ]]
    then printf "\nFAIL! `head -1 $HEADERS`\n"
    # exit 1
  else
    printf "\nPASSED! "
  fi
  # Check for a designer id for subsequent tests
  if [[ ! -z `get_designer_location` ]]
    then
    DESIGNER_ID=`get_designer_location`
  fi
  # Check for a token for subsequent tests
  if [[ ! -z `get_token` ]]
    then
    AUTH_TOKEN=`get_token`
  fi
  # Check for a storyboard id for subsequent tests
  if [[ ! -z `get_storyboard_location` ]]
    then
    STORYBOARD_ID=`get_storyboard_location`
  fi
  # Check for a sketch id for subsequent tests
  if [[ ! -z `get_sketch_location` ]]
    then
    SKETCH_ID=`get_sketch_location`
  fi
}
