#!/bin/bash
# designer 2 journey
mkdir -p tmp/api/$TEMP_VALUE_2;TRACE=tmp/api/$TEMP_VALUE_2/trace
HEADERS=tmp/api/$TEMP_VALUE_2.headers
SELF=$TEST_DESIGNER_2
printf "\n$SELF"

EXPECT="204 No Content" # when '/designers/:id' receives PUT request w/ avatar url and w/ designer's auth_token.
LINE_NUMBER=$LINENO
curl "$HOST/designers/$DESIGNER_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"avatar_url":"'$TEST_DESIGNER_2_AVATAR'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /designers/$DESIGNER_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/storyboards' receives POST request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/designers/$DESIGNER_ID/storyboards" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"name":"A Journey"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /designers/$DESIGNER_ID/storyboards $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards" -H "Auth-Token: $AUTH_TOKEN" -v -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /storyboards $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/sketches' receives POST request w/ sketch URL w/ storyboard id.
LINE_NUMBER=$LINENO
curl "$HOST/designers/$DESIGNER_ID/sketches" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"url":"https://s3.bucket.com/foo.jpg","storyboard_id":"'$STORYBOARD_ID'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /designers/$DESIGNER_ID/sketches $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/sketches' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/designers/$DESIGNER_ID/sketches" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /designers/$DESIGNER_ID/sketches $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/storyboards/:id/invite' receives POST request w/ new designer.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/invite" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"email":"'$TEST_DESIGNER_3'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /storyboards/$STORYBOARD_ID/invite $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/storyboards/:id/invite' receives POST request w/ new designer.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/invite" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"email":"'$TEST_DESIGNER_4'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /storyboards/$STORYBOARD_ID/invite $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/storyboards/:id/invite' receives POST request w/ new designer.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/invite" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"email":"'$TEST_DESIGNER_5'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /storyboards/$STORYBOARD_ID/invite $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/designers' receives GET request w/ designer id.
LINE_NUMBER=$LINENO
curl "$HOST/designers" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /designers $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards/:id/set-viewer' receives PUT request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/set-viewer" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "PUT /storyboards/$STORYBOARD_ID/set-viewer $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards/:id/get-viewers' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/get-viewers" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /storyboards/$STORYBOARD_ID/get-viewers $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/designers' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/designers" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /designers $LINE_NUMBER: Expecting: '$EXPECT'"
