#!/bin/bash
# user 3 journey (exceeds participants count for storyboard)
mkdir -p tmp/api/$TEMP_VALUE_3;TRACE=tmp/api/$TEMP_VALUE_3/trace
HEADERS=tmp/api/$TEMP_VALUE_3.headers
SELF=$TEST_USER_3

EXPECT="201 Created" # when '/users' receives POST request for new user.
LINE_NUMBER=$LINENO
curl "$HOST/users" -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"email":"'$SELF'","password":"pa55w0rd", "password_confirmation":"pa55w0rd"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /users $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/login' receives POST request to log in user.
LINE_NUMBER=$LINENO
curl "$HOST/login" -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"email":"'$SELF'","password":"pa55w0rd"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /login $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/users/:id' receives GET request w/ user's auth_token.
LINE_NUMBER=$LINENO
curl "$HOST/users/$USER_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /users/$USER_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="204 No Content" # when '/users/:id' receives PUT request w/ avatar url and w/ user's auth_token.
LINE_NUMBER=$LINENO
curl "$HOST/users/$USER_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"avatar_url":"'$TEST_USER_3_AVATAR'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /users/$USER_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="201 Created" # when '/sketches' receives POST request w/ sketch URL w/ storyboard id.
LINE_NUMBER=$LINENO
curl "$HOST/sketches" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"url":"https://s3.bucket.com/foo.jpg","storyboard_id":"'$STORYBOARD_ID'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "POST /sketches $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/sketches' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/sketches" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /sketches $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards" -H "Auth-Token: $AUTH_TOKEN" -v -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /storyboards $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="204 No Content" # when '/storyboards/:id' receives PUT request w/ participant.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"participant":"'$TEST_USER_1'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "PUT /storyboards/$STORYBOARD_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="204 No Content" # when '/storyboards/:id' receives PUT request w/ add'l participant who is a user.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"participant":"'$TEST_USER_2'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "PUT /storyboards/$STORYBOARD_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="422" # when '/storyboards/:id' receives PUT request w/ add'l participant who is not yet a user, and exceeds participants count for storyboard.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"participant":"user3friend@test.com"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "PUT /storyboards/$STORYBOARD_ID $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/users/:id/collaborators' receives GET request w/ user id.
LINE_NUMBER=$LINENO
curl "$HOST/users/$USER_ID/collaborators" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /users/$USER_ID/collaborators $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards/:id/set_viewer' receives PUT request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/set_viewer" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"participant":"'$SELF'"}' -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "PUT /storyboards/$STORYBOARD_ID/set_viewer $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards/:id/get_viewers' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards/$STORYBOARD_ID/get_viewers" -v -H "Auth-Token: $AUTH_TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /storyboards/$STORYBOARD_ID/get_viewers $LINE_NUMBER: Expecting: '$EXPECT'"

EXPECT="200 OK" # when '/storyboards' receives GET request w/ valid token.
LINE_NUMBER=$LINENO
curl "$HOST/storyboards" -H "Auth-Token: $AUTH_TOKEN" -v -H "Accept: application/json" -H "Content-type: application/json" -X GET -D $HEADERS --trace-ascii $TRACE.$LINE_NUMBER > /dev/null 2>&1
process_result
printf "GET /storyboards $LINE_NUMBER: Expecting: '$EXPECT'"
